name: 'Check Review'
on: # rebuild any PRs and main branch changes
  pull_request_review:
    types: [submitted]
jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          JIRA_ISSUE_REGEX: '.*(TUB-\d+).*'
          JIRA_URL: ${{secrets.JIRA_URL}}
          JIRA_USER: ${{secrets.JIRA_USER}}
          JIRA_PASSWORD: ${{secrets.JIRA_PASSWORD}}
          JIRA_WORKFLOW_ID: '61'
